vim.pack.add({ 'https://github.com/folke/which-key.nvim' })

local wk = require('which-key')
wk.setup({
  preset = 'helix',
  icons = vim.g.icons_enabled and { mappings = false } or {
    breadcrumb = '',
    separator = '->',
    group = '',
    ellipsis = '...',
    mappings = false,
    rules = false,
    colors = false,
    keys = {
      Up = 'Up ',
      Down = 'Down ',
      Left = 'Left ',
      Right = 'Right ',
      C = 'C-',
      M = 'M-',
      D = 'D-',
      S = 'S-',
      CR = 'CR ',
      Esc = 'Esc ',
      ScrollWheelDown = 'ScrollWD ',
      ScrollWheelUp = 'ScrollWU ',
      NL = 'NL ',
      BS = 'BS ',
      Space = 'SPC ',
      Tab = 'Tab ',
      F1 = 'F1',
      F2 = 'F2',
      F3 = 'F3',
      F4 = 'F4',
      F5 = 'F5',
      F6 = 'F6',
      F7 = 'F7',
      F8 = 'F8',
      F9 = 'F9',
      F10 = 'F10',
      F11 = 'F11',
      F12 = 'F12',
    },
  },
  win = {
    border = 'single',
    height = { min = 4, max = math.huge },
  },
})
wk.add({
  { '<leader>f', group = 'file' },
  { '<leader>s', group = 'search' },
  { '<leader>g', group = 'git' },
  { '<leader>gl', group = 'list' },
  { '<leader>h', group = 'hunk' },
  { '<leader>l', group = 'lsp' },
  { '<leader>t', group = 'toggle' },
  { '<leader>i', group = 'insert' },
})
