-- Load config modules that depend on plugins (all are loaded by now).
require('config.rooter')
require('config.lsp')
require('config.keymaps')
require('config.grep')
require('config.find')
require('config.cmdline')
require('config.picker')
require('config.compile')
require('config.statusline')
