local lush = require("lush")

local palette = {
    bar = "#1f1f27",
    base = "#cb9401",
    pop1 = "#70971e",
    pop2 = "#cb9401",
    back = "#161616",
    margin = "#161616",
    margin_hover = "#00ff00",
    margin_active = "#161616",
    list_item = "none",
    list_item_hover = "#171e20",
    list_item_hover_alt = "#0c0c0c",
    list_item_active = "#2d3640",
    list_item_active_alt = "#2d3640",
    cursor_green = "#00ee00",
    cursor_orange = "#ee7700",
    at_cursor = "#0c0c0c",
    highlight_cursor_line = "#1f1f27",
    highlight = "#315268",
    at_highlight = "#c4b82b",
    mark = "#494949",
    text_default = "#a08563",
    comment = "#686868",
    comment_pop_good = "#00a000",
    comment_pop_bad = "#a00000",
    keyword = "#ac7b0b",
    str_constant = "#6b8e23",
    preproc = "#dab98f",
    include = "#dab98f",
    special_character = "#ff0000",
    ghost_character = "#5b4d3c",
    highlight_junk = "#3a0000",
    highlight_white = "#003a3a",
    paste = "#ffbb00",
    undo = "#80005d",
    line_numbers_back = "#101010",
    line_numbers_text = "#404040",
    syntax_crap = "#907553",
    operators = "#907553",
    inactive_pane_background = "#161616",
    file_progress_bar = "#232323",
    brace_highlight = "#b09573",
    brace_line = "#9ba290",
    brace_annotation = "#9ba290",
    index_product_type = "#d9a51d",
    index_sum_type = "#d8a51d",
    index_function = "#cc5735",
    index_macro = "#478080",
    index_constant = "#6b8e23",
    index_comment_tag = "#00ff00",
    index_decl = "#c04047",
    cursor_macro = "#de2368",
    cursor_power_mode = "#efaf2f",
    cursor_inactive = "#880000",
    plot_cycle_1 = "#02a9ca",
    plot_cycle_2 = "#22b80b",
    plot_cycle_3 = "#f0bb0c",
    plot_cycle_4 = "#f0500c",
    token_highlight = "#f2d357",
    token_minor_highlight = "#d19045",
    error_annotation = "#ff0000",
    lego_grab = "#efaf6f",
    lego_splat = "#efaaef",
    comment_user_name = "#a0a0a0",
    text_cycle_1 = "#c0a583",
    text_cycle_2 = "#b09573",
    text_cycle_3 = "#f0bb0c",
    text_cycle_4 = "#02a9ca",
}

return lush(function(injected_functions)
    local sym = injected_functions.sym
    return {
        Normal { fg = palette.text_default, bg = palette.back },
        NormalNC { fg = palette.text_default, bg = palette.inactive_pane_background, blend = 8 },
        NormalFloat { fg = palette.text_default, bg = palette.margin },
        FloatBorder { fg = palette.margin_active, bg = palette.margin },
        WinSeparator { fg = palette.margin, bg = palette.back },
        WinBar { fg = palette.text_default, bg = palette.file_progress_bar },
        WinBarNC { fg = palette.line_numbers_text, bg = palette.margin },
        EndOfBuffer { fg = palette.margin, bg = palette.back },
        NonText { fg = palette.ghost_character, bg = palette.back },
        Whitespace { fg = palette.mark, bg = palette.back },

        SignColumn { fg = palette.ghost_character, bg = palette.back },
        LineNr { fg = palette.line_numbers_text, bg = palette.line_numbers_back },
        CursorLineNr { fg = palette.base, bg = palette.highlight_cursor_line,  },
        CursorLine { bg = palette.highlight_cursor_line },
        CursorColumn { CursorLine },
        ColorColumn { bg = palette.margin },
        FoldColumn { fg = palette.mark, bg = palette.margin },
        Folded { fg = palette.comment, bg = palette.margin },

        Cursor { fg = palette.at_cursor, bg = palette.cursor_green },
        lCursor { fg = palette.at_cursor, bg = palette.cursor_orange },
        CursorIM { fg = palette.at_cursor, bg = palette.cursor_orange },
        TermCursor { fg = palette.at_cursor, bg = palette.cursor_green },
        TermCursorNC { fg = palette.cursor_inactive, bg = palette.back },

        Visual { bg = palette.highlight },
        VisualNOS { Visual },
        Search { fg = palette.at_highlight, bg = palette.highlight },
        CurSearch { fg = palette.base, bg = palette.paste,  },
        IncSearch { CurSearch },
        Substitute { fg = palette.base, bg = palette.paste,  },
        MatchParen { fg = palette.brace_highlight, bg = palette.margin_active,  },

        Comment { fg = palette.comment },
        Constant { fg = palette.str_constant },
        String { fg = palette.str_constant },
        Character { fg = palette.str_constant },
        Number { fg = palette.str_constant },
        Float { fg = palette.str_constant },
        Boolean { fg = palette.index_macro },

        Identifier { fg = palette.text_default },
        Function { fg = palette.index_function },

        Statement { fg = palette.keyword },
        Conditional { fg = palette.keyword },
        Repeat { fg = palette.keyword },
        Label { fg = palette.keyword },
        Operator { fg = palette.operators },
        Keyword { fg = palette.keyword },
        Exception { fg = palette.keyword },

        PreProc { fg = palette.preproc },
        Include { fg = palette.include },
        Define { fg = palette.preproc },
        Macro { fg = palette.index_macro },
        PreCondit { fg = palette.preproc },

        Type { fg = palette.index_product_type },
        StorageClass { fg = palette.index_decl },
        Structure { fg = palette.index_sum_type },
        Typedef { fg = palette.index_decl },

        Special { fg = palette.index_decl },
        SpecialChar { fg = palette.special_character },
        Delimiter { fg = palette.brace_line },
        SpecialComment { fg = palette.comment_pop_good },
        Debug { fg = palette.cursor_macro },

        Underlined { fg = palette.plot_cycle_1, underline = true },
        Error { fg = palette.error_annotation, bg = palette.highlight_junk },
        Todo { fg = palette.comment_user_name, bg = palette.highlight,  },
        Title { fg = palette.base,  },

        ErrorMsg { fg = palette.error_annotation, bg = palette.highlight_junk },
        WarningMsg { fg = palette.cursor_power_mode },
        ModeMsg { fg = palette.base },
        MoreMsg { fg = palette.comment_pop_good },
        Question { fg = palette.comment_pop_good },

        StatusLine { fg = palette.base, bg = palette.bar,  },
        StatusLineNC { fg = palette.line_numbers_text, bg = palette.margin },
        TabLine { fg = palette.line_numbers_text, bg = palette.margin },
        TabLineSel { fg = palette.base, bg = palette.margin_active,  },
        TabLineFill { fg = palette.comment, bg = palette.back },

        Pmenu { fg = palette.text_default, bg = palette.list_item },
        PmenuSel { fg = palette.at_highlight, bg = palette.list_item_active,  },
        PmenuSbar { bg = palette.list_item_hover_alt },
        PmenuThumb { bg = palette.list_item_active_alt },

        WildMenu { fg = palette.at_highlight, bg = palette.list_item_active,  },
        Directory { fg = palette.plot_cycle_1 },
        Conceal { fg = palette.syntax_crap },
        SpecialKey { fg = palette.ghost_character },

        DiffAdd { fg = palette.comment_pop_good, bg = palette.highlight_white },
        DiffDelete { fg = palette.pop2, bg = palette.highlight_junk },
        DiffChange { fg = palette.keyword, bg = palette.list_item_hover },
        DiffText { fg = palette.at_highlight, bg = palette.token_highlight,  },
        Added { fg = palette.comment_pop_good },
        Removed { fg = palette.pop2 },
        Changed { fg = palette.keyword },

        SpellBad { sp = palette.pop2, undercurl = true },
        SpellCap { sp = palette.text_cycle_3, undercurl = true },
        SpellRare { sp = palette.text_cycle_4, undercurl = true },
        SpellLocal { sp = palette.text_cycle_2, undercurl = true },

        DiagnosticError { fg = palette.error_annotation },
        DiagnosticWarn { fg = palette.cursor_power_mode },
        DiagnosticInfo { fg = palette.plot_cycle_1 },
        DiagnosticHint { fg = palette.brace_line },
        DiagnosticOk { fg = palette.comment_pop_good },

        DiagnosticVirtualTextError { fg = palette.error_annotation, bg = palette.highlight_junk },
        DiagnosticVirtualTextWarn { fg = palette.cursor_power_mode, bg = palette.margin },
        DiagnosticVirtualTextInfo { fg = palette.plot_cycle_1, bg = palette.margin },
        DiagnosticVirtualTextHint { fg = palette.brace_line, bg = palette.margin },
        DiagnosticVirtualTextOk { fg = palette.comment_pop_good, bg = palette.margin },

        DiagnosticUnderlineError { sp = palette.error_annotation, undercurl = true },
        DiagnosticUnderlineWarn { sp = palette.cursor_power_mode, undercurl = true },
        DiagnosticUnderlineInfo { sp = palette.plot_cycle_1, undercurl = true },
        DiagnosticUnderlineHint { sp = palette.brace_line, undercurl = true },
        DiagnosticUnderlineOk { sp = palette.comment_pop_good, undercurl = true },

        GitSignsAdd { fg = palette.comment_pop_good, bg = palette.back },
        GitSignsChange { fg = palette.keyword, bg = palette.back },
        GitSignsDelete { fg = palette.pop2, bg = palette.back },

        TelescopeNormal { NormalFloat },
        TelescopeBorder { FloatBorder },
        TelescopeSelection { PmenuSel },
        TelescopeSelectionCaret { fg = palette.at_highlight, bg = palette.list_item_active },

        sym("@comment") { Comment },
        sym("@comment.documentation") { fg = palette.comment },
        sym("@comment.todo") { fg = palette.index_comment_tag,  },
        sym("@comment.note") { fg = palette.comment_user_name },
        sym("@comment.warning") { fg = palette.cursor_power_mode,  },
        sym("@comment.error") { fg = palette.comment_pop_bad,  },

        sym("@constant") { fg = palette.index_macro },
        sym("@constant.builtin") { fg = palette.index_macro },
        sym("@constant.macro") { fg = palette.index_macro },
        sym("@string") { fg = palette.str_constant },
        sym("@character") { fg = palette.str_constant },
        sym("@number") { fg = palette.str_constant },
        sym("@boolean") { fg = palette.index_macro },

        sym("@variable") { fg = palette.text_default },
        sym("@variable.builtin") { fg = palette.index_macro },
        sym("@variable.parameter") { fg = palette.base },
        sym("@property") { fg = palette.text_default },
        sym("@field") { fg = palette.text_default },

        sym("@function") { fg = palette.index_function },
        sym("@function.call") { fg = palette.index_function },
        sym("@function.macro") { fg = palette.index_macro },
        sym("@method") { fg = palette.index_function },
        sym("@constructor") { fg = palette.index_sum_type },
        sym("@macro") { fg = palette.index_macro },

        sym("@keyword") { fg = palette.keyword },
        sym("@keyword.function") { fg = palette.keyword },
        sym("@keyword.return") { fg = palette.keyword },
        sym("@operator") { fg = palette.operators },
        sym("@punctuation.bracket") { fg = palette.syntax_crap },
        sym("@punctuation.delimiter") { fg = palette.syntax_crap },
        sym("@punctuation.special") { fg = palette.syntax_crap },

        sym("@type") { fg = palette.index_product_type },
        sym("@type.builtin") { fg = palette.index_sum_type },
        sym("@type.definition") { fg = palette.index_decl },
        sym("@attribute") { fg = palette.lego_splat },
        sym("@namespace") { fg = palette.index_decl },
        sym("@module") { fg = palette.index_product_type },

        sym("@tag") { fg = palette.index_comment_tag },
        sym("@tag.attribute") { fg = palette.lego_grab },
        sym("@markup.heading") { fg = palette.base,  },
        sym("@markup.link") { fg = palette.plot_cycle_1, underline = true },
        sym("@markup.strong") {  },
        sym("@markup.italic") { italic = true },

        sym("@lsp.type.macro") { fg = palette.index_macro },
        sym("@lsp.type.function") { fg = palette.index_function },
        sym("@lsp.type.method") { fg = palette.index_function },
        sym("@lsp.type.parameter") { fg = palette.base },
        sym("@lsp.type.property") { fg = palette.text_default },
        sym("@lsp.type.type") { fg = palette.index_product_type },

        sym("@diff.plus") { Added },
        sym("@diff.minus") { Removed },
        sym("@diff.delta") { Changed },
    }
end)
