local lush = require("lush")

local palette = {
    back = "#161616",
    margin = "#262626",
    margin_hover = "#333333",
    margin_active = "#404040",
    cursor = "#40FF40",
    at_cursor = "#161616",
    highlight_cursor_line = "#101241",
    highlight = "#703419",
    mark = "#808080",
    default = "#A08563",
    at_highlight = "#CDAA7D",
    comment = "#7D7D7D",
    keyword = "#CD950C",
    str_constant = "#6B8E23",
    preproc = "#DAB98F",
    special_character = "#FF0000",
    ghost_character = "#5B4D3C",
    paste = "#FFBB00",
    undo = "#80005D",
    highlight_junk = "#3A0000",
    highlight_white = "#003A3A",
    bar = "#CACACA",
    bar_active = "#A8A8A8",
    base = "#000000",
    pop1 = "#03CF0C",
    pop2 = "#FF0000",
    text_cycle_1 = "#A00000",
    text_cycle_2 = "#00A000",
    text_cycle_3 = "#0020B0",
    text_cycle_4 = "#A0A000",
}

return lush(function()
    return {
        Normal { fg = palette.default, bg = palette.back },
        NormalNC { Normal },
        NormalFloat { fg = palette.default, bg = palette.margin },
        FloatBorder { fg = palette.margin_active, bg = palette.margin },
        WinSeparator { fg = palette.margin_active, bg = palette.back },
        EndOfBuffer { fg = palette.margin, bg = palette.back },
        NonText { fg = palette.ghost_character, bg = palette.back },
        Whitespace { fg = palette.margin_active, bg = palette.back },

        SignColumn { fg = palette.ghost_character, bg = palette.back },
        LineNr { fg = palette.margin_active, bg = palette.margin },
        CursorLineNr { fg = palette.bar_active, bg = palette.highlight_cursor_line, bold = true },
        CursorLine { bg = palette.highlight_cursor_line },
        CursorColumn { CursorLine },
        ColorColumn { bg = palette.margin_active },
        FoldColumn { fg = palette.mark, bg = palette.margin },
        Folded { fg = palette.comment, bg = palette.margin },

        Cursor { fg = palette.at_cursor, bg = palette.cursor },
        lCursor { Cursor },
        TermCursor { Cursor },
        TermCursorNC { fg = palette.cursor, bg = palette.back },

        Visual { bg = palette.highlight },
        VisualNOS { Visual },
        Search { fg = palette.at_highlight, bg = palette.highlight },
        CurSearch { fg = palette.base, bg = palette.paste, bold = true },
        IncSearch { CurSearch },
        Substitute { fg = palette.base, bg = palette.paste, bold = true },
        MatchParen { fg = palette.bar, bg = palette.margin_active, bold = true },

        Comment { fg = palette.comment },
        Constant { fg = palette.str_constant },
        String { fg = palette.str_constant },
        Character { fg = palette.str_constant },
        Number { fg = palette.str_constant },
        Float { fg = palette.str_constant },
        Boolean { fg = palette.str_constant },

        Identifier { fg = palette.default },
        Function { fg = palette.bar_active },

        Statement { fg = palette.keyword },
        Conditional { fg = palette.keyword },
        Repeat { fg = palette.keyword },
        Label { fg = palette.keyword },
        Operator { fg = palette.keyword },
        Keyword { fg = palette.keyword },
        Exception { fg = palette.keyword },

        PreProc { fg = palette.preproc },
        Include { fg = palette.str_constant },
        Define { fg = palette.preproc },
        Macro { fg = palette.preproc },
        PreCondit { fg = palette.preproc },

        Type { fg = palette.preproc },
        StorageClass { fg = palette.preproc },
        Structure { fg = palette.preproc },
        Typedef { fg = palette.preproc },

        Special { fg = palette.preproc },
        SpecialChar { fg = palette.special_character },
        Delimiter { fg = palette.mark },
        SpecialComment { fg = palette.comment },
        Debug { fg = palette.pop2 },

        Underlined { fg = palette.bar, underline = true },
        Error { fg = palette.pop2, bg = palette.highlight_junk },
        Todo { fg = palette.at_highlight, bg = palette.highlight, bold = true },
        Title { fg = palette.bar_active, bold = true },

        ErrorMsg { fg = palette.pop2, bg = palette.highlight_junk },
        WarningMsg { fg = palette.paste },
        ModeMsg { fg = palette.bar },
        MoreMsg { fg = palette.pop1 },
        Question { fg = palette.pop1 },

        StatusLine { fg = palette.bar, bg = palette.margin_active },
        StatusLineNC { fg = palette.comment, bg = palette.margin },
        TabLine { fg = palette.comment, bg = palette.margin },
        TabLineSel { fg = palette.bar_active, bg = palette.margin_active, bold = true },
        TabLineFill { fg = palette.comment, bg = palette.back },

        Pmenu { fg = palette.default, bg = palette.margin_hover },
        PmenuSel { fg = palette.at_highlight, bg = palette.margin_active, bold = true },
        PmenuSbar { bg = palette.margin },
        PmenuThumb { bg = palette.margin_active },

        WildMenu { fg = palette.at_highlight, bg = palette.margin_active, bold = true },
        Directory { fg = palette.text_cycle_3 },
        Conceal { fg = palette.ghost_character },
        SpecialKey { fg = palette.ghost_character },

        DiffAdd { fg = palette.pop1, bg = palette.highlight_white },
        DiffDelete { fg = palette.pop2, bg = palette.highlight_junk },
        DiffChange { fg = palette.keyword, bg = palette.margin_hover },
        DiffText { fg = palette.at_highlight, bg = palette.highlight, bold = true },
        Added { fg = palette.pop1 },
        Removed { fg = palette.pop2 },
        Changed { fg = palette.keyword },

        SpellBad { sp = palette.pop2, undercurl = true },
        SpellCap { sp = palette.text_cycle_3, undercurl = true },
        SpellRare { sp = palette.text_cycle_4, undercurl = true },
        SpellLocal { sp = palette.text_cycle_2, undercurl = true },

        DiagnosticError { fg = palette.pop2 },
        DiagnosticWarn { fg = palette.paste },
        DiagnosticInfo { fg = palette.bar },
        DiagnosticHint { fg = palette.mark },
        DiagnosticOk { fg = palette.pop1 },

        DiagnosticVirtualTextError { fg = palette.pop2, bg = palette.highlight_junk },
        DiagnosticVirtualTextWarn { fg = palette.paste, bg = palette.margin },
        DiagnosticVirtualTextInfo { fg = palette.bar, bg = palette.margin },
        DiagnosticVirtualTextHint { fg = palette.mark, bg = palette.margin },
        DiagnosticVirtualTextOk { fg = palette.pop1, bg = palette.margin },

        DiagnosticUnderlineError { sp = palette.pop2, undercurl = true },
        DiagnosticUnderlineWarn { sp = palette.paste, undercurl = true },
        DiagnosticUnderlineInfo { sp = palette.bar, undercurl = true },
        DiagnosticUnderlineHint { sp = palette.mark, undercurl = true },
        DiagnosticUnderlineOk { sp = palette.pop1, undercurl = true },

        GitSignsAdd { fg = palette.pop1, bg = palette.back },
        GitSignsChange { fg = palette.keyword, bg = palette.back },
        GitSignsDelete { fg = palette.pop2, bg = palette.back },

        TelescopeNormal { NormalFloat },
        TelescopeBorder { FloatBorder },
        TelescopeSelection { PmenuSel },
        TelescopeSelectionCaret { fg = palette.at_highlight, bg = palette.margin_active },
    }
end)
