vim.g.emacs_tab = false
vim.g.treesitter_enabled = true
vim.g.icons_enabled = false
vim.g.c_syntax_for_h = true
vim.g.mapleader = " "
vim.o.cursorline = true
vim.o.number = false
vim.o.relativenumber = false
vim.o.confirm = true
vim.o.wrap = false
vim.o.inccommand = "split"
vim.o.swapfile = false
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.list = false
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.signcolumn = "yes"
vim.o.foldcolumn = "0"
vim.o.mouse = "nv"
vim.o.breakindent = true
vim.o.smartindent = true
vim.o.autoindent = true
vim.o.termguicolors = true
vim.o.undofile = true
vim.o.undolevels = 10000
vim.o.scrolloff = 5
vim.o.updatetime = 250
vim.o.timeoutlen = 500
vim.opt.diffopt:append("linematch:60")
vim.o.cmdheight = 1
vim.o.showcmd = false
vim.o.exrc = true
vim.o.secure = true
vim.o.spelllang="en,pt_br"
