set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "niksingh710/minimal-tmux-status"
set -g @plugin "mrjones2014/smart-splits.nvim"

# Theme opts
set -g @minimal-tmux-status "top"
set -g @minimal-tmux-bg "default"
set -g @minimal-tmux-fg "#698DDA"

set-option -g default-terminal "$TERM"

# Ctrl+backspace support
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Undercurl
set -ga terminal-overrides ',xterm-256color:Tc'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

bind-key "s" run-shell "sesh connect \"$(
  sesh list | fzf-tmux -p 55%,60% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""

set -g status on
set -g mouse on
set -g history-limit 30000
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -s escape-time 0
set -gq allow-passthrough on
set-option -g status-position bottom
bind-key x kill-pane
set-option -g detach-on-destroy off

# Open the new panes in the current path
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# Reload conf
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded"

# Open floating window
bind-key p display-popup -w 80% -h 80% -E "tmux new-session -A -s scratch"

# smart-splits navigation + resize
set -g @smart-splits_move_left_key  'C-h'
set -g @smart-splits_move_down_key  'C-j'
set -g @smart-splits_move_up_key    'C-k'
set -g @smart-splits_move_right_key 'C-l'
set -g @smart-splits_resize_left_key  'M-h'
set -g @smart-splits_resize_down_key  'M-j'
set -g @smart-splits_resize_up_key    'M-k'
set -g @smart-splits_resize_right_key 'M-l'
set -g @smart-splits_resize_step_size '3'

run '~/.tmux/plugins/tpm/tpm'
